// ProjectIqraFrontend/wwwroot/libs/X6-dist/x6-react-shape/es/view.js
import React from 'react';
import { createPortal } from 'react-dom';
import { createRoot } from 'react-dom/client';
import { NodeView } from '@antv/x6';
import { Portal } from './portal';
import { Wrap } from './wrap';
export class ReactShapeView extends NodeView {
    targetId() {
        return `${this.graph.view.cid}:${this.cell.id}`;
    }
    getComponentContainer() {
        return this.selectors && this.selectors.foContent;
    }
    confirmUpdate(flag) {
        const ret = super.confirmUpdate(flag);
        return this.handleAction(ret, ReactShapeView.action, () => {
            this.renderReactComponent();
        });
    }
    renderReactComponent() {
        this.unmountReactComponent();
        const container = this.getComponentContainer();
        const node = this.cell;
        if (container) {
            const elem = React.createElement(Wrap, { node, graph: this.graph });
            if (Portal.isActive()) {
                const portal = createPortal(elem, container, node.id);
                Portal.connect(this.targetId(), portal);
            }
            else {
                this.root = createRoot(container);
                this.root.render(elem);
            }
        }
    }
    unmountReactComponent() {
        const container = this.getComponentContainer();
        if (container && this.root) {
            this.root.unmount();
            this.root = undefined;
        }
    }
    onMouseDown(e, x, y) {
        const target = e.target;
        const tagName = target.tagName.toLowerCase();
        if (tagName === 'input') {
            const type = target.getAttribute('type');
            if (type == null ||
                [
                    'text',
                    'password',
                    'number',
                    'email',
                    'search',
                    'tel',
                    'url',
                ].includes(type)) {
                return;
            }
        }
        super.onMouseDown(e, x, y);
    }
    unmount() {
        if (Portal.isActive()) {
            Portal.disconnect(this.targetId());
        }
        this.unmountReactComponent();
        super.unmount();
        return this;
    }
}
(function (ReactShapeView) {
    ReactShapeView.action = 'react';
    ReactShapeView.config({
        bootstrap: [ReactShapeView.action],
        actions: {
            component: ReactShapeView.action,
        },
    });
    NodeView.registry.register('react-shape-view', ReactShapeView, true);
})(ReactShapeView || (ReactShapeView = {}));
//# sourceMappingURL=view.js.map

// ProjectIqraFrontend/wwwroot/libs/X6-dist/x6-angular-shape/es/view.js
import { TemplateRef, ViewContainerRef, } from '@angular/core';
import { NodeView } from '@antv/x6';
import { registerInfo } from './registry';
export class AngularShapeView extends NodeView {
    getNodeContainer() {
        return this.selectors && this.selectors.foContent;
    }
    confirmUpdate(flag) {
        const ret = super.confirmUpdate(flag);
        return this.handleAction(ret, AngularShapeView.action, () => this.renderAngularContent());
    }
    getNgArguments() {
        var _a;
        const input = ((_a = this.cell.data) === null || _a === void 0 ? void 0 : _a.ngArguments) || {};
        return input;
    }
    /** 当执行 node.setData() 时需要对实例设置新的输入值 */
    setInstanceInput(content, ref) {
        const ngArguments = this.getNgArguments();
        if (content instanceof TemplateRef) {
            const embeddedViewRef = ref;
            embeddedViewRef.context = { ngArguments };
        }
        else {
            const componentRef = ref;
            Object.keys(ngArguments).forEach((v) => componentRef.setInput(v, ngArguments[v]));
            componentRef.changeDetectorRef.detectChanges();
        }
    }
    renderAngularContent() {
        const container = this.getNodeContainer();
        if (container) {
            this.unmountAngularContent();
            const node = this.cell;
            const { injector, content } = registerInfo.get(node.shape);
            const viewContainerRef = injector.get(ViewContainerRef);
            if (content instanceof TemplateRef) {
                const ngArguments = this.getNgArguments();
                const embeddedViewRef = viewContainerRef.createEmbeddedView(content, {
                    ngArguments,
                });
                embeddedViewRef.rootNodes.forEach((node) => container.appendChild(node));
                embeddedViewRef.detectChanges();
                node.on('change:data', () => this.setInstanceInput(content, embeddedViewRef));
            }
            else {
                const componentRef = viewContainerRef.createComponent(content, {
                    injector,
                });
                const insertNode = componentRef.hostView
                    .rootNodes[0];
                container.appendChild(insertNode);
                this.setInstanceInput(content, componentRef);
                node.on('change:data', () => this.setInstanceInput(content, componentRef));
                node.on('removed', () => componentRef.destroy());
            }
        }
    }
    unmountAngularContent() {
        const container = this.getNodeContainer();
        container.innerHTML = '';
        return container;
    }
    onMouseDown(e, x, y) {
        const target = e.target;
        const tagName = target.tagName.toLowerCase();
        if (tagName === 'input') {
            const type = target.getAttribute('type');
            if (type == null ||
                [
                    'text',
                    'password',
                    'number',
                    'email',
                    'search',
                    'tel',
                    'url',
                ].includes(type)) {
                return;
            }
        }
        super.onMouseDown(e, x, y);
    }
    unmount() {
        this.unmountAngularContent();
        super.unmount();
        return this;
    }
}
(function (AngularShapeView) {
    AngularShapeView.action = 'angular';
    AngularShapeView.config({
        bootstrap: [AngularShapeView.action],
        actions: {
            component: AngularShapeView.action,
        },
    });
    NodeView.registry.register('angular-shape-view', AngularShapeView, true);
})(AngularShapeView || (AngularShapeView = {}));
//# sourceMappingURL=view.js.map
